const express = require('express')
const path = require('path')
const bodyParser = require('body-parser')
const router = require('./router.js')
const app = express()

app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.use('/', router)
app.use(express.static(path.join(__dirname, '../static')))
app.listen(3000, () => console.log('Listening on port 3000!'))